[package]
description = "Ingestion tool for cirro"
edition.workspace = true
name = "cirro-graph"
repository.workspace = true
version.workspace = true

[dependencies]
clap.workspace = true
colored.workspace = true
fern.workspace = true
log.workspace = true
neo4rs = { version = "0.8.0", features = ["json"] }
rayon = "1.10"
rusqlite.workspace = true
rust-embed = { version = "8.11.0", features = ["compression"] }
serde.workspace = true
serde_json.workspace = true
serde_yaml = "0.9.34"
strum = "0.27.1"
strum_macros = "0.27.1"
tera = "1.20.1"
thiserror.workspace = true
tokio.workspace = true
url = "2.5.7"
uuid.workspace = true
