name: "Palo Alto Cloud NGFW Firewalls"
label: "{{ LABELS.PanCloudNgfwFirewall }}"
table_name: "resources"
resource_type: "paloaltonetworks.cloudngfw/firewalls"
properties:
  - "/id"
  - "/properties"
cypher: |
  UNWIND $batch AS row  
  MERGE (obj:{{ LABELS.ArmResource }} {id: toLower(row.id)})
  SET obj:{{ LABELS.PanCloudNgfwFirewall }}
  SET obj += {
      enableDnsProxy: row.properties.enableDnsProxy,
      enabledDnsType: row.properties.enabledDnsType,
      isPanoramaManaged: row.properties.isPanoramaManaged,
      isStrataCloudManaged: row.properties.isStrataCloudManaged,
      enableEgressNat: row.properties.networkProfile.enableEgressNat,
      networkType: row.properties.networkProfile.networkType
  }

  CALL (obj, row) {
    WHEN row.properties.associatedRulestack.resourceId IS NOT NULL THEN {
        MERGE (rs:{{ LABELS.ArmResource }} {id: toLower(row.properties.associatedRulestack.resourceId)})
        SET rs:{{ LABELS.PanCloudNgfwLocalRulestack }}
        MERGE (obj)-[:{{ REL.HAS_RULESTACK }}]->(rs)
    }
  }

  CALL (obj, row) {
      UNWIND coalesce(row.properties.networkProfile.publicIps, []) AS pubIps
      MERGE (p:{{ LABELS.ArmResource }} {id: toLower(pubIps.resourceId)})
      SET p:{{ LABELS.PublicIPAddress }}
      MERGE (obj)-[:{{ REL.HAS_IP }}]->(p)
  }