[workspace]
members = ["cirro", "cirro-ingest"]
resolver = "3"

[profile.release]
lto = "thin"
opt-level = "s"
panic = 'abort'
strip = true

# The profile that 'dist' will build with
[profile.dist]
codegen-units = 1
debug = false
incremental = false
inherits = "release"
lto = "fat"
opt-level = 3
overflow-checks = false
panic = "abort"
strip = true
