REL:
  APPROLE: "APPROLE"
  ASSOCIATED_WITH: "ASSOCIATED_WITH"
  AUTHENTICATES: "AUTHENTICATES"
  CONTAINS: "CONTAINS"
  FEDERATED_CREDENTIAL: "FEDERATED_CREDENTIAL"
  HAS_APPLICATION: "HAS_APPLICATION"
  HAS_APPROLE: "HAS_APPROLE"
  HAS_CONFIG: "HAS_CONFIG"
  HAS_DB: "HAS_DB"
  HAS_DNS_CONFIG: "HAS_DNS_CONFIG"
  HAS_ENDPOINT: "HAS_ENDPOINT"
  HAS_ENTITY: "HAS_ENTITY"
  HAS_EXTENSION: "HAS_EXTENSION"
  HAS_GATEWAY: "HAS_GATEWAY"
  HAS_IDENTITY: "HAS_IDENTITY"
  HAS_IP: "HAS_IP"
  HAS_KEY: "HAS_KEY"
  HAS_NIC: "HAS_NIC"
  HAS_NSG: "HAS_NSG"
  HAS_PARAMETER: "HAS_PARAMETER"
  HAS_PEERING: "HAS_PEERING"
  HAS_POLICY: "HAS_POLICY"
  HAS_PRIVATE_ENDPOINT: "HAS_PRIVATE_ENDPOINT"
  HAS_RESOURCE: "HAS_RESOURCE"
  HAS_RESTOREPOINT: "HAS_RESTOREPOINT"
  HAS_ROLE: "HAS_ROLE"
  HAS_ROUTE: "HAS_ROUTE"
  HAS_ROUTE_TABLE: "HAS_ROUTE_TABLE"
  HAS_RULE: "HAS_RULE"
  HAS_RUNBOOK: "HAS_RUNBOOK"
  HAS_SNAPSHOT: "HAS_SNAPSHOT"
  HAS_SOURCE: "HAS_SOURCE"
  HAS_SQL_VM: "HAS_SQL_VM"
  HAS_SUBNET: "HAS_SUBNET"
  HAS_SUBSCRIPTION: "HAS_SUBSCRIPTION"
  HAS_VERSION: "HAS_VERSION"
  HAS_VMAPP: "HAS_VMAPP"
  HOSTS: "HOSTS"
  HOSTS_SITE: "HOSTS_SITE"
  MANAGES: "MANAGES"
  MEMBER_OF: "MEMBER_OF"
  OWNS: "OWNS"
  PEERS_WITH: "PEERS_WITH"
  REFERENCES_PACKAGE: "REFERENCES_PACKAGE"
  REGISTERED_OWNER: "REGISTERED_OWNER"
  REGISTERED_USER: "REGISTERED_USER"
  REPRESENTED_BY: "REPRESENTED_BY"
  VERIFIED_DOMAIN: "VERIFIED_DOMAIN"

LABELS:
  # ARM Resource types
  ArmResource: "ArmResource"
  AutomationAccount: "AutomationAccount"
  AutomationRunbook: "AutomationRunbook"
  AvailabilitySet: "AvailabilitySet"
  ArcSqlServer: "ArcSqlServer"
  ArcSqlDB: "ArcSqlDB"
  BastionHost: "BastionHost"
  ClassicStorageAccount: "ClassicStorageAccount"
  CognitiveServices: "CognitiveServices"
  CommunicationServices: "CommunicationServices"
  ContainerRegistry: "ContainerRegistry"
  DataFactory: "DataFactory"
  Disk: "Disk"
  DnsZone: "DnsZone"
  EmailService: "EmailService"
  EmailServiceDomain: "EmailServiceDomain"
  EventGridTopic: "EventGridTopic"
  Gallery: "Gallery"
  GalleryApp: "GalleryApp"
  GalleryAppVersion: "GalleryAppVersion"
  HybridMachine: "HybridMachine"
  KeyVault: "KeyVault"
  ManagementGroup: "ManagementGroup"
  NetworkInterface: "NetworkInterface"
  NetworkSecurityGroup: "NetworkSecurityGroup"
  PrivateDnsZone: "PrivateDnsZone"
  PrivateEndpoint: "PrivateEndpoint"
  PublicIPAddress: "PublicIPAddress"
  RecoveryVault: "RecoveryVault"
  ResourceGroup: "ResourceGroup"
  RestorePointCollection: "RestorePointCollection"
  RouteTable: "RouteTable"
  ServerFarm: "ServerFarm"
  Snapshot: "Snapshot"
  SqlDatabase: "SqlDatabase"
  SqlServer: "SqlServer"
  SqlVirtualMachine: "SqlVirtualMachine"
  SSHPublicKey: "SSHPublicKey"
  StorageAccount: "StorageAccount"
  Subscription: "Subscription"
  Tenant: "Tenant"
  UserAssignedIdentity: "UserAssignedIdentity"
  VirtualMachine: "VirtualMachine"
  VirtualNetwork: "VirtualNetwork"
  VMApplication: "VMApplication"
  WebSite: "WebSite"

  # Graph objects
  GraphObject: "GraphObject"
  GraphApplication: "GraphApplication"
  GraphDevice: "GraphDevice" 
  GraphGroup: "GraphGroup"
  GraphRole: "GraphRole"
  GraphServicePrincipal: "GraphServicePrincipal"
  GraphUser: "GraphUser"
  GraphOrg: "GraphOrg"
  GraphPolicy: "GraphPolicy"
  GraphAdministrativeUnit: "GraphAdministrativeUnit"

  # Specialized node types. These are not ARM resources or Graph objects but are created from properties of those.
  BastionIPConfig: "BastionIPConfig"
  Certificate: "Certificate"
  ClientSecret: "ClientSecret"
  CustomDnsConfig: "CustomDnsConfig"
  FederatedIdentityCredential: "FederatedIdentityCredential"
  GraphAppRole: "GraphAppRole"
  HybridExtension: "HybridExtension"
  HybridIPAddress: "HybridIPAddress"
  IPConfiguration: "IPConfiguration"
  NetworkGateway: "NetworkGateway"
  NetworkPeering: "NetworkPeering"
  NetworkRoute: "NetworkRoute"
  NSGRule: "NSGRule"
  PrivateEndpointConnection: "PrivateEndpointConnection"
  PrivateLinkServiceConnection: "PrivateLinkServiceConnection"
  RunbookParameter: "RunbookParameter"
  ServicePrincipalEndpoint: "ServicePrincipalEndpoint"
  StorageAccountKey: "StorageAccountKey"
  Subnet: "Subnet"
  VerifiedDomain: "VerifiedDomain"
  VMExtension: "VMExtension"
  