name: "Administrative Units"
label: "{{ LABELS.GraphAdministrativeUnit }}"
table_name: "administrativeUnits"
properties:
  - "/id"
  - "/description"
  - "/displayName"
  - "/isMemberManagementRestricted"
  - "/members"
  - "/membershipRule"
  - "/membershipRuleProcessingState"
  - "/membershipType"
  - "/scopedRoleMembers"
  - "/visibility"
cypher: |
  UNWIND $batch as row
  MERGE (obj:{{ LABELS.GraphObject }} {id: toLower(row.id)})
  SET obj:{{ LABELS.GraphAdministrativeUnit }}
  SET obj += {
      description: row.description,
      displayName: row.displayName,
      isMemberManagementRestricted: row.isMemberManagementRestricted,
      membershipRule: row.membershipRule,
      membershipRuleProcessingState: row.membershipRuleProcessingState,
      membershipType: row.membershipType,
      visibility: row.visibility
  }

  WITH row, obj

  // Unwind members
  CALL (row, obj) {
    UNWIND coalesce(row.members, []) AS member
    MERGE (m:{{ LABELS.GraphObject }} {id: toLower(member)})
    MERGE (m)-[:{{ REL.MEMBER_OF }}]->(obj)
  }

  // Scoped role members
  CALL (row, obj) {
    UNWIND coalesce(row.scopedRoleMembers, []) AS srm
    MERGE (m:{{ LABELS.GraphObject }} {id: toLower(srm["roleMemberInfo/id"])})
    MERGE (m)-[r: {{ REL.HAS_SCOPED_ROLE }}]->(obj)
    SET r += {
        roleId: srm["roleId"]
    }
  }