name: "Graph Applications"
label: "{{ LABELS.GraphApplication }}"
table_name: "applications"
properties:
  - "/@odata.type"
  - "/appId"
  - "/appRoleAssignedTo"
  - "/appRoles"
  - "/applicationTemplateId"
  - "/description"
  - "/createdByAppId"
  - "/createdDateTime"
  - "/defaultRedirectUri"
  - "/displayName"
  - "/federatedIdentityCredentials"
  - "/identifierUris"
  - "/id"
  - "/isAuthorizationServiceEnabled"
  - "/isDeviceOnlyAuthSupported"
  - "/isDisabled"
  - "/isFallbackPublicClient"
  - "/isManagementRestricted"
  - "/keyCredentials"
  - "/nativeAuthenticationApisEnabled"
  - "/notes"
  - "/owners"
  - "/publicClient"
  - "/publisherDomain"
  - "/passwordCredentials"
  - "/signInAudience"
  - "/spa"
  - "/web"
constraint_properties:
    - "{{ LABELS.GraphAppRole }}:id"
    - "{{ LABELS.FederatedIdentityCredential }}:id"
    - "{{ LABELS.ClientSecret }}:keyId"
    - "{{ LABELS.Certificate }}:thumbprint"
cypher: |
    UNWIND $batch as row
    MERGE (obj:{{ LABELS.GraphObject }} {id: toLower(row.id)})
    SET obj:{{ LABELS.GraphApplication }}
    SET obj += {
        odataType: lower(row["@odata.type"]),
        displayName: row.displayName,
        appId: row.appId,
        description: row.description,
        notes: row.notes,
        createdDateTime: row.createdDateTime,
        createdByAppId: row.createdByAppId,
        applicationTemplateId: row.applicationTemplateId,
        isAuthorizationServiceEnabled: row.isAuthorizationServiceEnabled,
        isDeviceOnlyAuthSupported: row.isDeviceOnlyAuthSupported,
        isDisabled: row.isDisabled,
        isFallbackPublicClient: row.isFallbackPublicClient,
        isManagementRestricted: row.isManagementRestricted,
        nativeAuthenticationApisEnabled: row.nativeAuthenticationApisEnabled,
        publisherDomain: row.publisherDomain,
        signInAudience: row.signInAudience,
        identifierUris: row.identifierUris,
        defaultRedirectUri: row.web.redirectUris[0],
        redirectUris: row.web.redirectUris + row.spa.redirectUris + row.publicClient.redirectUris,
        publicClientRedirectUris: row.publicClient.redirectUris,
        spaRedirectUris: row.spa.redirectUris,
        webRedirectUris: row.web.redirectUris,
        implicitAccessToken: row.web.implicitGrantSettings.enableAccessTokenIssuance,
        implicitIdToken: row.web.implicitGrantSettings.enableIdTokenIssuance
    }

    WITH obj, row

    // App Roles
    CALL (obj, row) {
        UNWIND coalesce(row.appRoles, []) AS appRole
        MERGE (ar:{{ LABELS.GraphObject }} {id: toLower(appRole.id)})
        SET ar:{{ LABELS.GraphAppRole }}    
        SET ar += {
            allowedMemberTypes: appRole.allowedMemberTypes,
            description: appRole.description,
            displayName: appRole.displayName,
            isEnabled: appRole.isEnabled,
            isPreAuthorizationRequired: appRole.isPreAuthorizationRequired,
            isPrivate: appRole.isPrivate,
            origin: appRole.origin,
            value: appRole.value
        }
        MERGE (obj)-[:{{ REL.HAS_APPROLE }}]->(ar)
    }

    // Unwind owners
    CALL (obj, row) {
        UNWIND coalesce(row.owners, []) AS owner
        MERGE (ow:{{ LABELS.GraphObject }} {id: toLower(owner)})
        MERGE (ow)-[:{{ REL.OWNS }}]->(obj)
    }

    // Federated credentials
    CALL (obj, row) {
        UNWIND coalesce(row.federatedIdentityCredentials, []) AS fidc
        MERGE (f:{{ LABELS.FederatedIdentityCredential }} {id: toLower(fidc.id)})
        SET f += {
            audiences: fidc.audiences,
            description: fidc.description,
            issuer: fidc.issuer,
            name: fidc.name,
            subject: fidc.subject
        }
        MERGE (f)-[:{{ REL.AUTHENTICATES }}]->(obj)
    }

    // Unwind password credentials
    CALL (obj, row) {
        UNWIND coalesce(row.passwordCredentials, []) AS passwordCredential
        MERGE (p:{{ LABELS.ClientSecret }} {keyId: passwordCredential.keyId})
        SET p += {
            customKeyIdentifier: passwordCredential.customKeyIdentifier,
            displayName: passwordCredential.displayName,
            endDateTime: passwordCredential.endDateTime,
            hint: passwordCredential.hint,
            startDateTime: passwordCredential.startDateTime
        }
        MERGE (p)-[:{{ REL.AUTHENTICATES }}]->(obj)
    }

    // Unwind key credentials
    CALL (obj, row) {
        UNWIND coalesce([c IN coalesce(row.keyCredentials, []) WHERE c.customKeyIdentifier IS NOT NULL], []) AS keyCredential
        MERGE (k:{{ LABELS.Certificate }} {thumbprint: keyCredential.customKeyIdentifier})
        SET k += {
            displayName: keyCredential.displayName,
            endDateTime: keyCredential.endDateTime,
            startDateTime: keyCredential.startDateTime,
            type: keyCredential.type,
            usage: keyCredential.usage
        }
        MERGE (k)-[:{{ REL.AUTHENTICATES }}]->(obj)
    }

    // If createdByAppId exists, add created relationship to app that created this app
    // Assume it exists so MERGE
    CALL (obj, row) {
        WITH obj, row
        WHERE row.createdByAppId IS NOT NULL
        MERGE (creator:{{ LABELS.GraphObject }} {appId: toLower(row.createdByAppId)})
        MERGE (creator)-[:{{ REL.CREATED }}]->(obj)
    }
        