name: "Directory Roles"
label: "{{ LABELS.GraphRole }}"
table_name: "directoryRoles"
properties:
  - "/displayName"
  - "/id"
  - "/description"
  - "/roleTemplateId"
  - "/members"
cypher: |
    UNWIND $batch as row
    MERGE (obj:{{ LABELS.GraphObject }} {id: toLower(row.id)})
    SET obj:{{ LABELS.GraphRole }}
    SET obj += {
        displayName: row.displayName,
        description: row.description,
        roleTemplateId: row.roleTemplateId
    }

    WITH obj, row

    // Unwind members
    CALL (obj, row) {
        UNWIND coalesce(row.members, []) AS member
        MERGE (m:{{ LABELS.GraphObject }} {id: toLower(member)})
        MERGE (m)-[:{{ REL.HAS_ROLE }}]->(obj)
    }