name: "OAuth2 Permission Grants"
label: ""
table_name: "oauth2PermissionGrants"
properties:
  - "/id"
  - "/clientId"
  - "/consentType"
  - "/principalId"
  - "/resourceId"
  - "/scope"
  # These properties are currently ignored: https://learn.microsoft.com/en-us/graph/api/resources/oauth2permissiongrant?view=graph-rest-beta#properties
  - "/startTime"
  - "/expiryTime"
cypher: |
  UNWIND $batch AS row

  CALL (row) {
    WHEN row.principalId IS NULL THEN {
        MERGE (client:{{ LABELS.GraphObject }} {
            id: toLower(row.clientId)
        })
        MERGE (resource:{{ LABELS.GraphObject }} {
            id: toLower(row.resourceId)
        })
        MERGE (client)-[r:{{ REL.HAS_OAUTH_GRANT }}]->(resource)
        SET r += {
            id: row.id,
            scopes: split(btrim(row.scope), " "),
            consentType: row.consentType,
            principalId: row.principalId,
            startTime: row.startTime,
            expiryTime: row.expiryTime
        }
    }

    WHEN row.principalId IS NOT NULL THEN {
        MERGE (principal:{{ LABELS.GraphObject }} {
            id: toLower(row.principalId)
        })
        MERGE (client:{{ LABELS.GraphObject }} {
            id: toLower(row.clientId)
        })
        MERGE (resource:{{ LABELS.GraphObject }} {
            id: toLower(row.resourceId)
        })

        MERGE (principal)-[r:{{ REL.DELEGATED_TO_CLIENT }}]->(client)
        SET r += {
            id: row.id,
            scopes: split(btrim(row.scope), " "),
            consentType: row.consentType,
            principalId: row.principalId,
            startTime: row.startTime,
            expiryTime: row.expiryTime
        }

        MERGE (client)-[:{{ REL.HAS_USER_GRANT }}]->(resource)
    }
  }