package core

const (
	// Relationships
	AssociatedTo  = "AssociatedTo"
	AttachedTo    = "AttachedTo"
	Authenticates = "Authenticates"
	ConnectedTo   = "ConnectedTo"
	Contains      = "Contains"
	Exposes       = "Exposes"
	HasAccess     = "HasAccess"
	HasConfig     = "HasConfig"
	HasDisk       = "HasDisk"
	HasIdentity   = "HasIdentity"
	HasInstance   = "HasInstance"
	HasRbac       = "HasRbac"
	HasRole       = "HasRole"
	Manages       = "Manages"
	MemberOf      = "MemberOf"
	Owns          = "Owns"
	Represents    = "Represents"
	RepresentedBy = "RepresentedBy"
	Trusts        = "Trusts"
)

const (
	// Node labels
	GraphObject           = "GraphObject"
	GraphApplication      = "GraphApplication"
	GraphDevice           = "GraphDevice"
	GraphGroup            = "GraphGroup"
	GraphRole             = "GraphRole"
	GraphServicePrincipal = "GraphServicePrincipal"
	GraphUser             = "GraphUser"

	ArmResource          = "ArmResource"
	AutomationAccount    = "AutomationAccount"
	AzureRbac            = "AzureRbac"
	Disk                 = "Disk"
	IpConfiguration      = "IpConfiguration"
	KeyVault             = "KeyVault"
	ManagedIdentity      = "ManagedIdentity"
	NetworkInterface     = "NetworkInterface"
	NetworkSecurityGroup = "NetworkSecurityGroup"
	PublicIPAddress      = "PublicIPAddress"
	ResourceGroup        = "ResourceGroup"
	Runbook              = "Runbook"
	SSHPublicKey         = "SSHPublicKey"
	StorageAccount       = "StorageAccount"
	Subnet               = "Subnet"
	Subscription         = "Subscription"
	Tenant               = "Tenant"
	VirtualNetwork       = "VirtualNetwork"
	VirtualMachine       = "VirtualMachine"
)
