name: "Key Vault Secrets"
label: "{{ LABELS.KeyVaultSecret }}"
table_name: "keyVaultItems"
resource_type: "secret"
properties:
  - "/id"
  - "/name"
  - "/managed"
  - "/kid"
  - "/contentType"
  - "/attributes"
  - "/tags"
cypher: |
    UNWIND $batch AS row
    MERGE (obj:{{ LABELS.KeyVaultSecret }} {id: toLower(row.id)})
    SET obj += {
        name: row.name,
        managed: row.managed,
        contentType: row.contentType,
        kid: row.kid,
        enabled: row.attributes.enabled,
        notBefore: row.attributes.notBefore,
        expires: row.attributes.expires,
        created: row.attributes.created,
        updated: row.attributes.updated,
        recoverableDays: row.attributes.recoverableDays,
        recoveryLevel: row.attributes.recoveryLevel,
        tags: [key IN keys(row.tags) | key + ":" + row.tags[key]]
    }

    // Relationship to parent Key Vault
    // We can merge on KeyVault.vaultUri since the secret metadata doesn't include a direct reference to the vault ARM resource ID
    // KeyVault.vaultUri format: https://{vault-name}.vault.azure.net/
    // Secret id format: https://{vault-name}.vault.azure.net/secrets/{secret-name}
    WITH obj, row
    MERGE (vault:{{ LABELS.KeyVault }} {vaultUri: toLower(substring(row.id, 0, apoc.text.indexOf(row.id, "secrets/")))})
    MERGE (vault)-[:{{ REL.HAS_SECRET }}]->(obj)
    
    RETURN count(*) AS _