name: "Key Vault Secret Values"
label: "{{ LABELS.KeyVaultSecretValue }}"
table_name: "keyVaultItems"
resource_type: "secretvalue"
properties:
  - "/id"
  - "/name"
  - "/managed"
  - "/kid"
  - "/value"
  - "/contentType"
  - "/attributes"
  - "/tags"
cypher: |
    UNWIND $batch AS row
    MERGE (obj:{{ LABELS.KeyVaultSecretValue }} {id: toLower(row.id)})

    SET obj += {
        name: row.name,
        value: row.value,
        managed: row.managed,
        contentType: row.contentType,
        kid: row.kid,
        enabled: row.attributes.enabled,
        notBefore: row.attributes.notBefore,
        expires: row.attributes.expires,
        created: row.attributes.created,
        updated: row.attributes.updated,
        recoverableDays: row.attributes.recoverableDays,
        recoveryLevel: row.attributes.recoveryLevel,
        tags: [key IN keys(row.tags) | key + ":" + row.tags[key]]
    }

    // Relationship to parent Key Vault Secret
    // Key Vault Secret id format: https://{vault-name}.vault.azure.net/secrets/{secret-name}
    // Key Vault Secret Value id format: {KeyVaultSecret}/{version}
    // Use replace to strip the version from the secret value id to get the parent secret id
    WITH obj, row
    WITH obj, row, toLower(apoc.text.replace(row.id, '/[^/]+$', '')) AS secretId
    MERGE (secret:{{ LABELS.KeyVaultSecret }} {id: secretId})
    MERGE (secret)-[:{{ REL.HAS_VERSION }}]->(obj)
    RETURN count(*) AS _