REL:
  ASSIGNED_APPROLE: "ASSIGNED_APPROLE"
  ASSOCIATED_WITH: "ASSOCIATED_WITH"
  AUTHENTICATES: "AUTHENTICATES"
  CAN_ACCESS_REGISTRY: "CAN_ACCESS_REGISTRY"
  CONTAINS: "CONTAINS"
  CONTAINS_IMAGE: "CONTAINS_IMAGE"
  DELEGATED_TO_CLIENT: "DELEGATED_TO_CLIENT"
  DEPLOYS: "DEPLOYS"
  ENCRYPTED_BY: "ENCRYPTED_BY"
  FEDERATED_CREDENTIAL: "FEDERATED_CREDENTIAL"
  HAS_ALERT: "HAS_ALERT"
  HAS_APPLICATION: "HAS_APPLICATION"
  HAS_APPROLE: "HAS_APPROLE"
  HAS_BUILDER: "HAS_BUILDER"
  HAS_CERTIFICATE: "HAS_CERTIFICATE"
  HAS_CONFIG: "HAS_CONFIG"
  HAS_CONTAINER: "HAS_CONTAINER"
  HAS_DB: "HAS_DB"
  HAS_DNS_CONFIG: "HAS_DNS_CONFIG"
  HAS_ENDPOINT: "HAS_ENDPOINT"
  HAS_ENTITY: "HAS_ENTITY"
  HAS_ENVVAR: "HAS_ENVVAR"
  HAS_EXTENSION: "HAS_EXTENSION"
  HAS_DFS_FILESYSTEM: "HAS_DFS_FILESYSTEM"
  HAS_GATEWAY: "HAS_GATEWAY"
  HAS_GALLERY_IMAGE: "HAS_GALLERY_IMAGE"
  HAS_GITHUB_SETTING: "HAS_GITHUB_SETTING"
  HAS_IDENTITY: "HAS_IDENTITY"
  HAS_INSTANCE: "HAS_INSTANCE"
  HAS_IP: "HAS_IP"
  HAS_KEY: "HAS_KEY"
  HAS_LINKED_DOMAIN: "HAS_LINKED_DOMAIN"
  HAS_NIC: "HAS_NIC"
  HAS_NSG: "HAS_NSG"
  HAS_OAUTH_GRANT: "HAS_OAUTH_GRANT"
  HAS_ORACLE_RESOURCE: "HAS_ORACLE_RESOURCE"
  HAS_PARAMETER: "HAS_PARAMETER"
  HAS_PEERING: "HAS_PEERING"
  HAS_POLICY: "HAS_POLICY"
  HAS_PRIVATE_ENDPOINT: "HAS_PRIVATE_ENDPOINT"
  HAS_RESOURCE: "HAS_RESOURCE"
  HAS_RESTOREPOINTS: "HAS_RESTOREPOINTS"
  HAS_ROLE: "HAS_ROLE"
  HAS_ROUTE: "HAS_ROUTE"
  HAS_ROUTE_TABLE: "HAS_ROUTE_TABLE"
  HAS_RULE: "HAS_RULE"
  HAS_RULESTACK: "HAS_RULESTACK"
  HAS_RUN_COMMAND: "HAS_RUN_COMMAND"
  HAS_RUNBOOK: "HAS_RUNBOOK"
  HAS_SCOPED_ROLE: "HAS_SCOPED_ROLE"
  HAS_SECRET: "HAS_SECRET"
  HAS_SNAPSHOT: "HAS_SNAPSHOT"
  HAS_SOURCE: "HAS_SOURCE"
  HAS_SQL_VM: "HAS_SQL_VM"
  HAS_SUBNET: "HAS_SUBNET"
  HAS_SUBSCRIPTION: "HAS_SUBSCRIPTION"
  HAS_USER_GRANT: "HAS_USER_GRANT"
  HAS_VERSION: "HAS_VERSION"
  HAS_VMAPP: "HAS_VMAPP"
  HOSTS: "HOSTS"
  HOSTS_SITE: "HOSTS_SITE"
  IS_ADMIN: "IS_ADMIN"
  IS_DEPLOYED: "IS_DEPLOYED"
  IS_RBAC_ELIGIBLE: "IS_RBAC_ELIGIBLE"
  IS_ROLE_ELIGIBLE: "IS_ROLE_ELIGIBLE"
  MANAGES: "MANAGES"
  MATCHES_CERT: "MATCHES_CERT"
  MATCHES_SECRET: "MATCHES_SECRET"
  MEMBER_OF: "MEMBER_OF"
  MOUNTS: "MOUNTS"
  OWNS: "OWNS"
  PEERS_WITH: "PEERS_WITH"
  REFERENCES_PACKAGE: "REFERENCES_PACKAGE"
  REGISTERED_BY: "REGISTERED_BY"
  REGISTERED_OWNER: "REGISTERED_OWNER"
  REGISTERED_USER: "REGISTERED_USER"
  REPRESENTED_BY: "REPRESENTED_BY"
  SAME_USER: "SAME_USER"
  USED_BY: "USED_BY"
  USES_CERTIFICATE: "USES_CERTIFICATE"
  USES_KEY_VAULT: "USES_KEY_VAULT"
  USES_STORAGE: "USES_STORAGE"  
  USES_STORAGE_DFS: "USES_STORAGE_DFS"
  VERIFIED_DOMAIN: "VERIFIED_DOMAIN"

LABELS:
  # ARM Resource types
  ActivityLogAlert: "ActivityLogAlert"
  AfdEndpoint: "AfdEndpoint"
  AnalysisServiceServer: "AnalysisServiceServer"
  ApimService: "ApimService"
  AppBuilder: "AppBuilder"
  AppConfigurationStore: "AppConfigurationStore"
  AppManagedEnvironment: "AppManagedEnvironment"
  ArmResource: "ArmResource"
  AutomationAccount: "AutomationAccount"
  AutomationRunbook: "AutomationRunbook"
  AvailabilitySet: "AvailabilitySet"
  ArcSqlServer: "ArcSqlServer"
  ArcSqlDB: "ArcSqlDB"
  AzureStackEdgeMachine: "AzureStackEdgeMachine"
  AzureStackRegistration: "AzureStackRegistration"
  BastionHost: "BastionHost"
  B2CDirectory: "B2CDirectory"
  CAPNamedLocation: "CAPNamedLocation"
  CdnProfile: "CdnProfile"
  ClassicStorageAccount: "ClassicStorageAccount"
  CognitiveServices: "CognitiveServices"
  ConditionalAccessPolicy: "ConditionalAccessPolicy"
  CommServiceDomain: "CommServiceDomain"
  CommunicationServices: "CommunicationServices"
  ComputeImage: "ComputeImage"
  Container: "Container"
  ContainerApp: "ContainerApp"
  ContainerGroup: "ContainerGroup"
  ContainerImage: "ContainerImage"
  ContainerRegistry: "ContainerRegistry"
  DataFactory: "DataFactory"
  Disk: "Disk"
  DiskEncryptionSet: "DiskEncryptionSet"
  DocumentDB: "DocumentDB"
  DnsZone: "DnsZone"
  EmailService: "EmailService"
  EnvVar: "EnvVar"
  EventGridTopic: "EventGridTopic"
  EventHubNamespace: "EventHubNamespace"
  ExpressRouteCircuit: "ExpressRouteCircuit"
  FabricCapacity: "FabricCapacity"
  Gallery: "Gallery"
  GalleryApp: "GalleryApp"
  GalleryAppVersion: "GalleryAppVersion"
  GalleryImage: "GalleryImage"
  GalleryImageVersion: "GalleryImageVersion"
  GithubNetworkSettings: "GithubNetworkSettings"
  GrafanaDashboard: "GrafanaDashboard"
  HybridGateway: "HybridGateway"
  HybridMachine: "HybridMachine"
  HybridExtension: "HybridExtension"
  HybridPrivateLinkScope: "HybridPrivateLinkScope"
  KeyVault: "KeyVault"
  KeyVaultSecret: "KeyVaultSecret"
  KeyVaultSecretValue: "KeyVaultSecretValue"
  KeyVaultCertificate: "KeyVaultCertificate"
  KeyVaultCertificateValue: "KeyVaultCertificateValue"
  KustoCluster: "KustoCluster"
  ManagementGroup: "ManagementGroup"
  ManagedHSM: "ManagedHSM"
  MLWorkspace: "MLWorkspace"
  NetAppAccount: "NetAppAccount"
  NetAppCapacityPool: "NetAppCapacityPool"
  NetAppSnapshotPolicy: "NetAppSnapshotPolicy"
  NetAppVolume: "NetAppVolume"
  NetworkInterface: "NetworkInterface"
  NetworkSecurityGroup: "NetworkSecurityGroup"
  NetworkWatcher: "NetworkWatcher"
  OracleAutonomousDB: "OracleAutonomousDB"
  PanCloudNgfwFirewall: "PanCloudNgfwFirewall"
  PanCloudNgfwLocalRulestack: "PanCloudNgfwLocalRulestack"
  PrivateDnsZone: "PrivateDnsZone"
  PrivateEndpoint: "PrivateEndpoint"
  PublicIPAddress: "PublicIPAddress"
  PurviewAccount: "PurviewAccount"
  RecoveryVault: "RecoveryVault"
  RedisCache: "RedisCache"
  ResourceGroup: "ResourceGroup"
  RestorePoint: "RestorePoint"
  RestorePointCollection: "RestorePointCollection"
  RouteTable: "RouteTable"
  SaasResource: "SaaSResource"
  ServerFarm: "ServerFarm"
  ServiceBusNamespace: "ServiceBusNamespace"
  SignalR: "SignalR"
  Snapshot: "Snapshot"
  SqlDatabase: "SqlDatabase"
  SqlServer: "SqlServer"
  SqlVirtualMachine: "SqlVirtualMachine"
  SSHPublicKey: "SSHPublicKey"
  StaticWebsite: "StaticWebsite"
  StorageAccount: "StorageAccount"
  StorageAccountDFS: "StorageAccountDFS"
  Subscription: "Subscription"
  SynapseWorkspace: "SynapseWorkspace"
  SyntexDocumentProcessor: "SyntexDocumentProcessor"
  Tenant: "Tenant"
  UserAssignedIdentity: "UserAssignedIdentity"
  VirtualMachine: "VirtualMachine"
  VirtualNetwork: "VirtualNetwork"
  VisualStudioAccount: "VisualStudioAccount"
  VMApplication: "VMApplication"
  VMScaleSet: "VMScaleSet"
  WebSite: "WebSite"
  WebCertificate: "WebCertificate"

  # Graph objects
  GraphObject: "GraphObject"
  GraphApplication: "GraphApplication"
  GraphDevice: "GraphDevice" 
  GraphGroup: "GraphGroup"
  GraphRole: "GraphRole"
  GraphServicePrincipal: "GraphServicePrincipal"
  GraphUser: "GraphUser"
  GraphOrg: "GraphOrg"
  GraphPolicy: "GraphPolicy"
  GraphAdministrativeUnit: "GraphAdministrativeUnit"

  # Specialized Azure node types. These are not ARM resources or Graph objects but are created from properties of those.
  AnalysisServiceFirewallRule: "AnalysisServiceFirewallRule"
  AzureStackEdgeMachineNic: "AzureStackEdgeMachineNic"
  BastionIPConfig: "BastionIPConfig"
  Certificate: "Certificate"
  ClientSecret: "ClientSecret"
  CustomDnsConfig: "CustomDnsConfig"
  ExpressRouteCircuitPeering: "ExpressRouteCircuitPeering"
  FederatedIdentityCredential: "FederatedIdentityCredential"
  GraphAppRole: "GraphAppRole"
  HybridIPAddress: "HybridIPAddress"
  HybridRunCommand: "HybridRunCommand"
  HybridRunCommandParameter: "HybridRunCommandParameter"
  IPConfiguration: "IPConfiguration"
  NetAppAccountADDomain: "NetAppAccountADDomain"
  NetAppVolumeMount: "NetAppVolumeMount"
  NetworkGateway: "NetworkGateway"
  NetworkPeering: "NetworkPeering"
  NetworkRoute: "NetworkRoute"
  NSGRule: "NSGRule"
  PrivateEndpointConnection: "PrivateEndpointConnection"
  PrivateLinkServiceConnection: "PrivateLinkServiceConnection"
  RegistryCredential: "RegistryCredential"
  RunbookParameter: "RunbookParameter"
  ServicePrincipalEndpoint: "ServicePrincipalEndpoint"
  StorageAccountKey: "StorageAccountKey"
  Subnet: "Subnet"
  VerifiedDomain: "VerifiedDomain"
  VMExtension: "VMExtension"
  VMRunCommand: "VMRunCommand"
  VMRunCommandParameter: "VMRunCommandParameter"

  # Tailscale nodes
  TSUser: "TSUser"
  TSDevice: "TSDevice"
  TSTailnet: "TSTailnet"
  