name: "Hybrid Machine Run Commands"
label: "{{ LABELS.HybridRunCommand }}"
table_name: "resources"
resource_type: "microsoft.compute/virtualmachines/runcommands"
properties:
  - "/id"
  - "/properties"
index_properties:
  - "{{ LABELS.HybridRunCommandParameter }}:name+commandId"
cypher: |
    UNWIND $batch AS row
    MERGE (obj:{{ LABELS.ArmResource }} {id: toLower(row.id)})
    SET obj:{{ LABELS.HybridRunCommand }}

    SET obj += {
        asyncExecution: row.properties.asyncExecution,
        runAsUser: row.properties.runAsUser,
        timeoutInSeconds: row.properties.timeoutInSeconds,
        treatFailureAsDeploymentFailure: row.properties.treatFailureAsDeploymentFailure,
        script: row.properties.source.script,
        output: row.properties.instanceView.output
    }

    WITH obj, row, split(toLower(obj.id), '/runcommands/')[0] AS vmId
    MERGE (vm:{{ LABELS.ArmResource }} {id: toLower(vmId)})
    SET vm:{{ LABELS.HybridMachine }}
    MERGE (vm)-[:{{ REL.HAS_RUN_COMMAND }}]->(obj)

    WITH obj, row
    CALL {
        WITH obj, row
        UNWIND coalesce(row.properties.parameters, []) AS param
        MERGE (p:{{ LABELS.HybridRunCommandParameter }} {name: param.name, commandId: toLower(obj.id)})
        SET p.value = param.value

        MERGE (obj)-[:{{ REL.HAS_PARAMETER }}]->(p)
        RETURN count(*) AS _
    }
    RETURN count(*) AS _