name: "Hybrid Machine Extensions"
label: "{{ LABELS.HybridExtension }}"
table_name: "resources"
resource_type: "microsoft.hybridcompute/machines/extensions"
properties:
  - "/id"
  - "/properties"
cypher: |
    UNWIND $batch AS row
    MERGE (obj:{{ LABELS.ArmResource }} {id: toLower(row.id)})
    SET obj:{{ LABELS.HybridExtension }}

    SET obj += {
        extType: row.properties.type,
        autoUpgradeMinorVersion: row.properties.autoUpgradeMinorVersion,
        enableAutomaticUpgrade: row.properties.enableAutomaticUpgrade,
        statusMessage: row.properties.instanceView.status.message,
        provisioningState: row.properties.provisioningState,
        publisher: row.properties.publisher,
        settings: apoc.convert.toJson(row.properties.settings)
    }