name: "Deduplicate Storage Accounts by Name"
label: "PostProcessingDeduplicateStorageAccountsByName"
priority: 1000
cypher: |
  CALL apoc.periodic.iterate(
    "
    MATCH (n:{{ LABELS.StorageAccount }})
    WHERE n.name IS NOT NULL
    WITH toLower(n.name) AS lid, collect(n) AS ns
    WHERE size(ns) > 1
    RETURN lid, ns
    ",
    "
    WITH lid, ns
    WITH
        head(ns) AS keep,
        tail(ns) AS dups,
        lid
    UNWIND dups AS d
    CALL apoc.refactor.mergeNodes(
        [keep, d],
        {properties:'combine', mergeRels:true}
    )
    YIELD node
    // Ensure names are lowercase
    SET keep.name = lid
    RETURN 1
  ",
  {batchSize: 1000, parallel: false}
  )