name: "Deduplicate Container Registries by Server"
label: "PostProcessingDeduplicateContainerRegistriesByServer"
priority: 1000
cypher: |
  CALL apoc.periodic.iterate(
    "
    MATCH (n:{{ LABELS.ContainerRegistry }})
    WHERE n.loginServer IS NOT NULL
    WITH toLower(n.loginServer) AS lid, collect(n) AS ns
    WHERE size(ns) > 1
    RETURN lid, ns
    ",
    "
    WITH lid, ns
    WITH
        head(ns) AS keep,
        tail(ns) AS dups,
        lid
    UNWIND dups AS d
    CALL apoc.refactor.mergeNodes(
        [keep, d],
        {properties:'combine', mergeRels:true}
    )
    YIELD node
    // Ensure loginServers are lowercase
    SET keep.loginServer = lid
    RETURN 1
  ",
  {batchSize: 1000, parallel: false}
  )