name: "Match Vault Secrets to Client Secrets"
label: "PostProcessingMatchVaultSecretsToClientSecrets"
priority: 1000
cypher: |
  CALL apoc.periodic.iterate(
    "
    MATCH (c:{{ LABELS.ClientSecret }})
    MATCH (s:{{ LABELS.KeyVaultSecretValue }})
    WHERE substring(s.value, 0, 3) = c.hint AND substring(s.value, 3, 3) IN ['7Q~', '8Q~']
    RETURN c, s
    ",
    "
    WITH c, s
    MERGE (s)-[:{{ REL.MATCHES_SECRET }}]->(c)
    RETURN 1
    ",
    {batchSize:1000, parallel:false}
  )