name: "Merge VMs by vmId"
label: "PostProcessingMergeVMsByVmId"
priority: 1000
cypher: |
  CALL apoc.periodic.iterate(
    "
    MATCH (n:{{ LABELS.VirtualMachine }})
    WHERE n.vmId IS NOT NULL
    WITH toLower(n.vmId) AS lid, collect(n) AS ns
    WHERE size(ns) > 1
    RETURN lid, ns
    ",
    "
    WITH lid, ns
    WITH
        head(ns) AS keep,
        tail(ns) AS dups,
        lid
    UNWIND dups AS d
    CALL apoc.refactor.mergeNodes(
        [keep, d],
        {properties:'combine', mergeRels:true}
    )
    YIELD node
    // Ensure vmIds are lowercase
    SET keep.vmId = lid
    RETURN 1
  ",
  {batchSize: 1000, parallel: false}
  )