name: "Snapshots"
label: "{{ LABELS.Snapshot }}"
table_name: "resources"
resource_type: "microsoft.compute/snapshots"
properties:
  - "/id"
  - "/properties"
cypher: |
    UNWIND $batch AS row
    MERGE (obj:{{ LABELS.ArmResource }} {id: row.id})
    SET obj:{{ LABELS.Snapshot }}
    SET obj += {
        createOption: row.properties.creationData.createOption,
        dataAccessAuthMode: row.properties.dataAccessAuthMode,
        diskSizeBytes: row.properties.diskSizeBytes,
        diskSizeGB: row.properties.diskSizeGB,
        diskState: row.properties.diskState,
        hyperVGeneration: row.properties.hyperVGeneration,
        incremental: row.properties.incremental,
        networkAccessPolicy: row.properties.networkAccessPolicy,
        osType: row.properties.osType,
        publicNetworkAccess: row.properties.publicNetworkAccess
    }

    MERGE (h:{{ LABELS.ArmResource }} {id: row.properties.creationData.sourceResourceId})
    MERGE (h)-[:{{ REL.HAS_SNAPSHOT }}]->(obj)