name: "Web Certificates"
label: "{{ LABELS.WebCertificate }}"
table_name: "resources"
resource_type: "microsoft.web/certificates"
properties:
  - "/id"
  - "/properties"
cypher: |
  UNWIND $batch AS row  
  MERGE (obj:{{ LABELS.ArmResource }} {id: toLower(row.id)})
  SET obj:{{ LABELS.WebCertificate }}
  SET obj += {
      cerBlob: row.properties.cerBlob,
      expirationDate: row.properties.expirationDate,
      friendlyName: row.properties.friendlyName,
      hostNames: row.properties.hostNames,
      issueDate: row.properties.issueDate,
      issuer: row.properties.issuer,
      keyVaultId: row.properties.keyVaultId,
      keyVaultSecretName: row.properties.keyVaultSecretName,
      keyVaultSecretStatus: row.properties.keyVaultSecretStatus,
      password: row.properties.password,
      pfxBlob: row.properties.pfxBlob,
      publicKeyHash: row.properties.publicKeyHash,
      subjectName: row.properties.subjectName,
      thumbprint: row.properties.thumbprint,
      valid: row.properties.valid
  }

  // If the Key Vault ID is present, create a relationship to the Key Vault and Key Vault Secret
  WITH obj, row WHERE row.properties.keyVaultId IS NOT NULL AND row.properties.keyVaultSecretName IS NOT NULL
  MERGE (kv:{{ LABELS.ArmResource }} {id: toLower(row.properties.keyVaultId)})
  SET kv:{{ LABELS.KeyVault }}

  MERGE (kvs:{{ LABELS.KeyVaultSecret }} {id: toLower(row.properties.keyVaultId + "/secrets/" + row.properties.keyVaultSecretName)})

  // Create relationship from Key Vault to Key Vault Secret
  MERGE (kv)-[:{{ REL.HAS_SECRET }}]->(kvs)

  // Create relationship from Web Certificate to Key Vault Secret
  MERGE (kvs)-[:{{ REL.USED_BY }}]->(obj)