services:
  cirro-neo4j:
    build:
      context: .
      dockerfile: Dockerfile.neo4j
    image: cirro-neo4j:latest
    container_name: cirro-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"

  cirro-neodash:
    image: neo4jlabs/neodash:latest
    container_name: cirro-neodash
    restart: unless-stopped
    depends_on:
      - cirro-neo4j
    ports:
      - "5005:5005"
