# Use the latest official Neo4j image
FROM neo4j:latest

# Install openssl for generating SSL certificates
RUN apt-get update && apt-get install -y openssl

# Set environment variables for Neo4j authentication and APOC plugin
# This username/password should not be used in production
ENV NEO4J_AUTH=neo4j/password
ENV NEO4J_PLUGINS='["apoc"]'

# Configure SSL
ENV NEO4J_server_https_enabled=true
ENV NEO4J_server_http_enabled=false
ENV NEO4J_dbms_ssl_policy_https_enabled=true
ENV NEO4J_dbms_ssl_policy_https_base__directory=/ssl/https

ENV NEO4J_server_bolt_tls__level=OPTIONAL
ENV NEO4J_dbms_ssl_policy_bolt_enabled=true
ENV NEO4J_dbms_ssl_policy_bolt_base__directory=/ssl/bolt
ENV NEO4J_dbms_ssl_policy_bolt_client__auth=NONE


# Create the directories for the certs
RUN mkdir -p /ssl/https/trusted && mkdir -p /ssl/bolt/trusted && mkdir -p /ssl/https/revoked && mkdir -p /ssl/bolt/revoked
RUN chown -R neo4j:neo4j /ssl

# Create the certs
RUN openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /ssl/https/private.key -out /ssl/https/public.crt -subj "/C=US/ST=AZ/L=Tempe/O=Bishop Fox/OU=Cirro/CN=Cirro" -addext "subjectAltName=DNS:localhost"
RUN openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /ssl/bolt/private.key -out /ssl/bolt/public.crt -subj "/C=US/ST=AZ/L=Tempe/O=Bishop Fox/OU=Cirro/CN=Cirro" -addext "subjectAltName=DNS:localhost"
RUN chmod 444 /ssl/bolt/private.key
RUN chmod 444 /ssl/https/private.key
RUN cp /ssl/https/public.crt /ssl/https/trusted
RUN cp /ssl/bolt/public.crt /ssl/bolt/trusted
RUN chgrp -R 7474 /ssl && chmod -R g+rx /ssl

# Expose the default ports
EXPOSE 7473 7687

CMD ["neo4j"]