# Use the latest official Neo4j image
FROM neo4j:latest

# Set environment variables for Neo4j authentication and APOC plugin
# This username/password should not be used in production
ENV NEO4J_AUTH=neo4j/password
ENV NEO4J_PLUGINS='["apoc"]'

# Expose the default ports
EXPOSE 7474 7687

CMD ["neo4j"]