name: "Disk Encryption Sets"
label: "{{ LABELS.DiskEncryptionSet }}"
table_name: "resources"
resource_type: "microsoft.compute/diskencryptionsets"
properties:
  - "/id"
  - "/sku"
  - "/properties"
cypher: |
    UNWIND $batch AS row
    MERGE (obj:{{ LABELS.ArmResource }} {id: toLower(row.id)})
    SET obj:{{ LABELS.DiskEncryptionSet }}
    SET obj += {
        activeKey: row.properties.activeKey.keyUrl,
        encryptionType: row.properties.encryptionType,
        lastKeyRotationTimestamp: row.properties.lastKeyRotationTimestamp,
        rotationToLatestKeyVersionEnabled: row.properties.rotationToLatestKeyVersionEnabled
    }

    WITH obj, row
    CALL (obj, row) {
        WITH obj, row WHERE row.properties.activeKey.sourceVault.id IS NOT NULL
        MERGE (kv:{{ LABELS.ArmResource }} {id: toLower(row.properties.activeKey.sourceVault.id)})
        SET kv:{{ LABELS.KeyVault }}
        MERGE (obj)-[r:{{ REL.USES_KEY_VAULT }}]->(kv)
        SET r += {
            target: obj.activeKey
        }
    }