name: "Gallery Image Versions"
label: "{{ LABELS.GalleryImageVersion }}"
table_name: "resources"
resource_type: "microsoft.compute/galleries/images/versions"
properties:
  - "/id"
  - "/properties"
cypher: |
    UNWIND $batch AS row
    MERGE (obj:{{ LABELS.ArmResource }} {id: toLower(row.id)})
    SET obj:{{ LABELS.GalleryImageVersion }}
    SET obj += {
        excludedFromLatest: row.properties.publishingProfile.excludedFromLatest,
        publishedDate: row.properties.publishingProfile.publishedDate,
        replicaCount: row.properties.publishingProfile.replicaCount,
        storageAccountType: row.properties.publishingProfile.storageAccountType
    }

    CALL (obj, row) {
        WITH obj, row WHERE row.properties.storageProfile.osDiskImage.source.id IS NOT NULL
        MERGE (ci:{{ LABELS.ArmResource }} {id: toLower(row.properties.storageProfile.osDiskImage.source.id)})
        MERGE (obj)-[:{{ REL.HAS_SOURCE }}]->(ci)
    }

    CALL (obj, row) {
        WITH obj, row WHERE row.properties.storageProfile.source.id IS NOT NULL
        MERGE (ci:{{ LABELS.ArmResource }} {id: toLower(row.properties.storageProfile.source.id)})
        SET ci:{{ LABELS.ComputeImage }}
        MERGE (obj)-[:{{ REL.HAS_SOURCE }}]->(ci)
    }