name: "Route Tables"
label: "{{ LABELS.RouteTable }}"
table_name: "resources"
resource_type: "microsoft.network/routetables"
properties:
  - "/id"
  - "/properties"
cypher: |
    UNWIND $batch AS row
    MERGE (obj:{{ LABELS.ArmResource }} {id: toLower(row.id)})
    SET obj:{{ LABELS.RouteTable }}
    SET obj += {
        disableBgpRoutePropagation: row.properties.disableBgpRoutePropagation
    }

    WITH obj, row
        CALL {
            WITH obj, row
            UNWIND coalesce(row.properties.routes, []) AS route
            MERGE (r:{{ LABELS.NetworkRoute }} {id: toLower(route.id)})
            SET r += {
                name: route.name,
                type: route.type,
                addressPrefix: route.properties.addressPrefix,
                nextHopType: route.properties.nextHopType,
                nextHopIpAddress: route.properties.nextHopIpAddress,
                hasBgpOverride: route.properties.hasBgpOverride
            }
            MERGE (obj)-[:{{ REL.HAS_ROUTE }}]->(r)
            RETURN count(*) AS _
        }

    WITH obj, row
        CALL {
            WITH obj, row
            UNWIND coalesce(row.properties.subnets, []) AS subnet
            MERGE (s:{{ LABELS.Subnet }} {id: toLower(subnet.id)})
            MERGE (s)-[:{{ REL.HAS_ROUTE_TABLE }}]->(obj)
            RETURN count(*) AS _
        }
    RETURN count(*) AS _